### ISSUE TITLE
Additional Fields not working #1

### ISSUE THREAD

**Issue by felipelbhering** [selesnow/rappsflyer#1]
Hello selesnow

I tried several funcitons such as af_get_aggregate_data, af_get_raw_data and others and it seems it's not working the additional fields parameter. Tried to add "Campaign type" and others - ("is_organic" and the columns ) but the data (additional fields) doesn't come.
one example
af_get_aggregate_data( date_from = "2021-08-01",
date_to="2021-08-31",
report_type="daily_report",
app_id = "(my_id)",
additional_fields = c("af_adset",
"af_ad",
"af_ad_type",
"city","state",
"is_organic",
"Conversion type",
"Channel",
"Campaign type"))

colnames(agr_data)
[1] "Date" "Agency/PMD (af_prt)" "Media Source (pid)" "Campaign (c)" "Impressions" "Clicks"
[7] "CTR" "Installs" "Conversion Rate" "Sessions" "Loyal Users" "Loyal Users/Installs"
[13] "Total Cost" "Average eCPI"

Also it only comes non-organic data, is it possible to get organic data from appsflyers with this package?
Thank you,
Felipe

**Comment by selesnow** [comment]
It seems to me that you are using incorrect names of additional fields, see the [help](https://support.appsflyer.com/hc/en-us/articles/207034346#aggregate-report-uri-and-parameters) on working with pull API.
